{
  xdg.configFile = {
    blender-theme = {
      target = "blender/5.0/scripts/presets/interface_theme/nordic_gold.xml";

      text = ''
        <bpy>
          <Theme>
            <user_interface>
              <ThemeUserInterface
                menu_shadow_fac="0.4"
                menu_shadow_width="6"
                icon_alpha="1"
                icon_saturation="1"
                widget_emboss="#00000026"
                editor_border="#292a34"
                editor_outline="#3b425215"
                editor_outline_active="#ffffff2a"
                widget_text_cursor="#bf616a"
                panel_roundness="0.5"
                panel_header="#383f4fff"
                panel_title="#eceff4"
                panel_text="#e5e9f0"
                panel_back="#3b4252ff"
                panel_sub_back="#00000024"
                panel_outline="#00000000"
                panel_active="#4772b3ff"
                transparent_checker_primary="#3b4252"
                transparent_checker_secondary="#2e3440"
                transparent_checker_size="4"
                axis_x="#bf616a"
                axis_y="#a3be8c"
                axis_z="#5e81ac"
                axis_w="#edba18"
                gizmo_hi="#ffffff"
                gizmo_primary="#f5f14d"
                gizmo_secondary="#63ffff"
                gizmo_view_align="#ffffff"
                gizmo_a="#4da84d"
                gizmo_b="#a33535"
                icon_scene="#e5e9f0ff"
                icon_collection="#eceff4ff"
                icon_object="#d08770ff"
                icon_object_data="#a3be8cff"
                icon_modifier="#88c0d0ff"
                icon_shading="#bf616aff"
                icon_folder="#ebcb8bff"
                icon_autokey="#ab3c48ff"
                icon_border_intensity="0.01"
                >
                <wcol_regular>
                  <ThemeWidgetColors
                    outline="#434c5eff"
                    outline_sel="#3d3d3dff"
                    inner="#434c5eff"
                    inner_sel="#a27c35ff"
                    item="#2e3440ff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="0"
                    shadedown="-5"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_regular>
                <wcol_tool>
                  <ThemeWidgetColors
                    outline="#434c5eff"
                    outline_sel="#3d3d3dff"
                    inner="#434c5eff"
                    inner_sel="#a27c35ff"
                    item="#ffffffff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="0"
                    shadedown="-5"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_tool>
                <wcol_toolbar_item>
                  <ThemeWidgetColors
                    outline="#3b4252ff"
                    outline_sel="#3d3d3dff"
                    inner="#3b4252ff"
                    inner_sel="#a27c35ff"
                    item="#e6e6e6cc"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="0"
                    shadedown="0"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_toolbar_item>
                <wcol_radio>
                  <ThemeWidgetColors
                    outline="#434c5eff"
                    outline_sel="#3d3d3dff"
                    inner="#434c5eff"
                    inner_sel="#a27c35ff"
                    item="#ffffffff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="5"
                    shadedown="-5"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_radio>
                <wcol_text>
                  <ThemeWidgetColors
                    outline="#434c5eff"
                    outline_sel="#3d3d3dff"
                    inner="#434c5eff"
                    inner_sel="#5e81acff"
                    item="#a27c3533"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="-3"
                    shadedown="0"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_text>
                <wcol_option>
                  <ThemeWidgetColors
                    outline="#434c5eff"
                    outline_sel="#3d3d3dff"
                    inner="#434c5eff"
                    inner_sel="#a27c35ff"
                    item="#ffffffff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="0"
                    shadedown="-15"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_option>
                <wcol_toggle>
                  <ThemeWidgetColors
                    outline="#434c5eff"
                    outline_sel="#3d3d3dff"
                    inner="#434c5eff"
                    inner_sel="#a27c35ff"
                    item="#191919ff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="0"
                    shadedown="0"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_toggle>
                <wcol_num>
                  <ThemeWidgetColors
                    outline="#434c5eff"
                    outline_sel="#3d3d3dff"
                    inner="#434c5eff"
                    inner_sel="#5e81acff"
                    item="#a27c35ff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="0"
                    shadedown="0"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_num>
                <wcol_numslider>
                  <ThemeWidgetColors
                    outline="#434c5eff"
                    outline_sel="#3d3d3dff"
                    inner="#434c5eff"
                    inner_sel="#434c5eff"
                    item="#a27c35ff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="TRUE"
                    shadetop="-4"
                    shadedown="0"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_numslider>
                <wcol_box>
                  <ThemeWidgetColors
                    outline="#3b4252ff"
                    outline_sel="#3d3d3dff"
                    inner="#3b4252ff"
                    inner_sel="#5e81acff"
                    item="#2e3440ff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="0"
                    shadedown="0"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_box>
                <wcol_curve>
                  <ThemeWidgetColors
                    outline="#727272ff"
                    outline_sel="#9a9a9aff"
                    inner="#545454ff"
                    inner_sel="#000000ff"
                    item="#00000059"
                    text="#080808"
                    text_sel="#c9c9c9"
                    show_shaded="FALSE"
                    shadetop="0"
                    shadedown="0"
                    roundness="0.4"
                    >
                  </ThemeWidgetColors>
                </wcol_curve>
                <wcol_menu>
                  <ThemeWidgetColors
                    outline="#434c5eff"
                    outline_sel="#3d3d3dff"
                    inner="#434c5eff"
                    inner_sel="#a27c35b3"
                    item="#d9d9d9ff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="10"
                    shadedown="-10"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_menu>
                <wcol_pulldown>
                  <ThemeWidgetColors
                    outline="#434c5e00"
                    outline_sel="#3d3d3d00"
                    inner="#434c5eff"
                    inner_sel="#a27c35b3"
                    item="#3b4252ff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="25"
                    shadedown="-20"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_pulldown>
                <wcol_menu_back>
                  <ThemeWidgetColors
                    outline="#3b4252ff"
                    outline_sel="#242424ff"
                    inner="#3b4252ff"
                    inner_sel="#a27c35ff"
                    item="#3b4252ff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="25"
                    shadedown="-20"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_menu_back>
                <wcol_pie_menu>
                  <ThemeWidgetColors
                    outline="#3b4252ff"
                    outline_sel="#242424ff"
                    inner="#3b4252f0"
                    inner_sel="#a27c35ff"
                    item="#88c0d0ff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="10"
                    shadedown="-10"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_pie_menu>
                <wcol_tooltip>
                  <ThemeWidgetColors
                    outline="#2e3440ff"
                    outline_sel="#242424ff"
                    inner="#2e3440ff"
                    inner_sel="#a27c35ff"
                    item="#19191aef"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="25"
                    shadedown="-20"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_tooltip>
                <wcol_menu_item>
                  <ThemeWidgetColors
                    outline="#434c5e00"
                    outline_sel="#3d3d3d00"
                    inner="#00000000"
                    inner_sel="#a27c35ff"
                    item="#ffffff8f"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="38"
                    shadedown="0"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_menu_item>
                <wcol_scroll>
                  <ThemeWidgetColors
                    outline="#2e3440ff"
                    outline_sel="#3d3d3dff"
                    inner="#2e344040"
                    inner_sel="#2e344040"
                    item="#4c566aff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="5"
                    shadedown="-5"
                    roundness="1"
                    >
                  </ThemeWidgetColors>
                </wcol_scroll>
                <wcol_progress>
                  <ThemeWidgetColors
                    outline="#3b4252ff"
                    outline_sel="#3d3d3dff"
                    inner="#3b4252ff"
                    inner_sel="#a27c35ff"
                    item="#a27c35ff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="0"
                    shadedown="0"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_progress>
                <wcol_list_item>
                  <ThemeWidgetColors
                    outline="#434c5e00"
                    outline_sel="#2d2d2dff"
                    inner="#434c5eff"
                    inner_sel="#5e81acff"
                    item="#a27c3533"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="0"
                    shadedown="0"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_list_item>
                <wcol_state>
                  <ThemeWidgetStateColors
                    error="#771111ff"
                    warning="#ac8737ff"
                    info="#28487dff"
                    success="#188625ff"
                    inner_anim="#53992e"
                    inner_anim_sel="#38a600"
                    inner_key="#b3ae36"
                    inner_key_sel="#b29700"
                    inner_driven="#9000cc"
                    inner_driven_sel="#9900e6"
                    inner_overridden="#00c3c3"
                    inner_overridden_sel="#118f8f"
                    inner_changed="#cc7529"
                    inner_changed_sel="#d26400"
                    blend="0.5"
                    >
                  </ThemeWidgetStateColors>
                </wcol_state>
                <wcol_tab>
                  <ThemeWidgetColors
                    outline="#2e3440ff"
                    outline_sel="#1d1d1dff"
                    inner="#333945ff"
                    inner_sel="#5e81acff"
                    item="#2d2d2dff"
                    text="#eceff4"
                    text_sel="#ffffff"
                    show_shaded="FALSE"
                    shadetop="0"
                    shadedown="0"
                    roundness="0.5"
                    >
                  </ThemeWidgetColors>
                </wcol_tab>
              </ThemeUserInterface>
            </user_interface>
            <regions>
              <ThemeRegions>
                <asset_shelf>
                  <ThemeRegionsAssetShelf
                    back="#303030e6"
                    header_back="#1d1d1dff"
                    >
                  </ThemeRegionsAssetShelf>
                </asset_shelf>
                <channels>
                  <ThemeRegionsChannels
                    back="#2e3440"
                    text="#b8b8b8"
                    text_selected="#ffaf29"
                    >
                  </ThemeRegionsChannels>
                </channels>
                <scrubbing>
                  <ThemeRegionsScrubbing
                    back="#2e3440ff"
                    text="#a6a6a6"
                    time_marker="#00000060"
                    time_marker_selected="#ffffff60"
                    >
                  </ThemeRegionsScrubbing>
                </scrubbing>
                <sidebars>
                  <ThemeRegionsSidebars
                    back="#3b425200"
                    tab_back="#2e344000"
                    >
                  </ThemeRegionsSidebars>
                </sidebars>
              </ThemeRegions>
            </regions>
            <common>
              <ThemeCommon>
                <anim>
                  <ThemeCommonAnim
                    playhead="#a27c35"
                    preview_range="#d0877066"
                    scene_strip_range="#00000080"
                    channels="#0f2c4d24"
                    channels_sub="#143e6624"
                    channel_group="#2f5d1f44"
                    channel_group_active="#36802455"
                    channel="#4c566aff"
                    channel_selected="#60c04044"
                    keyframe="#e8e8e8"
                    keyframe_selected="#ebcb8b"
                    keyframe_extreme="#e8b3cc"
                    keyframe_extreme_selected="#f28080"
                    keyframe_breakdown="#b3dbe8"
                    keyframe_breakdown_selected="#54bfed"
                    keyframe_jitter="#94e575"
                    keyframe_jitter_selected="#61c042"
                    keyframe_moving_hold="#5c5656"
                    keyframe_moving_hold_selected="#ffaf23"
                    keyframe_generated="#585858"
                    keyframe_generated_selected="#a28962"
                    long_key="#b6aa58ff"
                    long_key_selected="#ebcb8bff"
                    >
                  </ThemeCommonAnim>
                </anim>
                <curves>
                  <ThemeCommonCurves
                    handle_free="#000000"
                    handle_sel_free="#000000"
                    handle_auto="#909000"
                    handle_sel_auto="#f0ff40"
                    handle_vect="#409030"
                    handle_sel_vect="#40c030"
                    handle_align="#803060"
                    handle_sel_align="#f090a0"
                    handle_auto_clamped="#994030"
                    handle_sel_auto_clamped="#f0af90"
                    handle_vertex="#000000"
                    handle_vertex_select="#ff8500"
                    handle_vertex_size="5"
                    >
                  </ThemeCommonCurves>
                </curves>
              </ThemeCommon>
            </common>
            <view_3d>
              <ThemeView3D
                grid="#4c566a4d"
                clipping_border_3d="#313131ff"
                wire="#000000"
                wire_edit="#000000"
                edge_width="1"
                gp_wire_edit="#99999980"
                gp_vertex="#000000"
                gp_vertex_select="#ff8500"
                gp_vertex_size="3"
                text_grease_pencil="#b5e61d"
                object_selected="#d08770"
                object_active="#d06746"
                camera="#000000"
                empty="#000000"
                light="#00000050"
                speaker="#000000"
                vertex="#000000"
                vertex_select="#ff7a00"
                vertex_size="3"
                edge_select="#ffa000"
                edge_mode_select="#ffd800"
                face="#ffffff02"
                face_select="#ffa5522e"
                face_mode_select="#ffb70033"
                facedot_size="3"
                face_back="#ff0000b3"
                face_front="#0000ffb3"
                bevel="#00a5ff"
                seam="#db2512"
                sharp="#00ffff"
                crease="#cc0099"
                freestyle="#7fff7f4d"
                extra_edge_len="#150806"
                extra_edge_angle="#4d4d00"
                extra_face_angle="#0000cc"
                extra_face_area="#004d00"
                editmesh_active="#ffffff33"
                normal="#22dddd"
                vertex_normal="#2361dd"
                split_normal="#dd23dd"
                vertex_unreferenced="#000000"
                face_retopology="#50c8ff0f"
                nurb_uline="#909000"
                nurb_vline="#803060"
                nurb_sel_uline="#f0ff40"
                nurb_sel_vline="#f090a0"
                bone_pose="#50c8ff"
                bone_pose_active="#8cffff"
                bone_solid="#b2b2b2"
                bone_locked_weight="#ff000080"
                before_current_frame="#f22e23"
                after_current_frame="#78f244"
                bundle_solid="#c8c8c8"
                camera_path="#000000"
                camera_passepartout="#000000"
                skin_root="#b44d4d"
                view_overlay="#000000"
                transform="#ffffff"
                outline_width="1"
                object_origin_size="6"
                >
                <space>
                  <ThemeSpaceGradient
                    title="#eceff4"
                    text="#e5e9f0"
                    text_hi="#ffffff"
                    header="#3b4252ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                    <gradients>
                      <ThemeGradientColors
                        background_type="SINGLE_COLOR"
                        high_gradient="#2e3440"
                        gradient="#2e3440"
                        >
                      </ThemeGradientColors>
                    </gradients>
                  </ThemeSpaceGradient>
                </space>
              </ThemeView3D>
            </view_3d>
            <graph_editor>
              <ThemeGraphEditor
                grid="#4c566a"
                vertex="#000000"
                vertex_select="#ff8500"
                vertex_active="#ffffff"
                vertex_size="6"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#ffffff"
                    text="#a6a6a6"
                    text_hi="#ffffff"
                    header="#2e3440ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeGraphEditor>
            </graph_editor>
            <file_browser>
              <ThemeFileBrowser
                selected_file="#a27c35"
                row_alternate="#ffffff07"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#ffffff"
                    text="#e6e6e6"
                    text_hi="#ffffff"
                    header="#2e3440ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeFileBrowser>
            </file_browser>
            <nla_editor>
              <ThemeNLAEditor
                grid="#3b4252"
                active_action="#d0877066"
                active_action_unset="#9987614d"
                strips="#0c0a0a"
                strips_selected="#d08770"
                transition_strips="#1c2630"
                transition_strips_selected="#2e75db"
                meta_strips="#332642"
                meta_strips_selected="#692196"
                sound_strips="#2b3d3d"
                sound_strips_selected="#1f7a7a"
                tweak="#a3be8c"
                tweak_duplicate="#bf616a"
                keyframe_border="#000000ff"
                keyframe_border_selected="#000000ff"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#ffffff"
                    text="#dadada"
                    text_hi="#ffffff"
                    header="#3b4252ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeNLAEditor>
            </nla_editor>
            <dopesheet_editor>
              <ThemeDopeSheet
                grid="#4c566a"
                keyframe_border="#000000ff"
                keyframe_border_selected="#000000ff"
                keyframe_scale_factor="1"
                summary="#bf616a66"
                anim_interpolation_linear="#94e575cc"
                anim_interpolation_constant="#e59c7bcc"
                anim_interpolation_other="#5dbabeb3"
                simulated_frames="#721e65ff"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#eeeeee"
                    text="#a6a6a6"
                    text_hi="#ffffff"
                    header="#3b4252ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeDopeSheet>
            </dopesheet_editor>
            <image_editor>
              <ThemeImageEditor
                grid="#2e3440ff"
                vertex="#000000"
                vertex_select="#ff8500"
                vertex_size="3"
                face="#ffffff0a"
                face_select="#ff85003c"
                face_mode_select="#00000000"
                facedot_size="3"
                editmesh_active="#ffffff40"
                wire_edit="#c0c0c0"
                edge_width="1"
                edge_select="#ff8500"
                scope_back="#727272ff"
                preview_stitch_face="#7f7f0033"
                preview_stitch_edge="#ff00ff33"
                preview_stitch_vert="#0000ff33"
                preview_stitch_stitchable="#00ff00ff"
                preview_stitch_unstitchable="#ff0000ff"
                preview_stitch_active="#e1d2c323"
                uv_shadow="#707070ff"
                metadatabg="#000000"
                metadatatext="#ffffff"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#ffffff"
                    text="#eceff4"
                    text_hi="#ffffff"
                    header="#3b4252ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeImageEditor>
            </image_editor>
            <sequence_editor>
              <ThemeSequenceEditor
                grid="#4c566a"
                movie_strip="#4d6890"
                movieclip_strip="#8f4c4c"
                image_strip="#8f744b"
                scene_strip="#828f50"
                audio_strip="#4c8f8f"
                effect_strip="#514a73"
                transition_strip="#867acc"
                color_strip="#8f8f8f"
                meta_strip="#5b4d91"
                mask_strip="#666666"
                text_strip="#824c8f"
                active_strip="#d9d9d9"
                selected_strip="#ff8f0d"
                keyframe_border="#000000ff"
                keyframe_border_selected="#000000ff"
                preview_back="#2e3440"
                metadatabg="#000000"
                metadatatext="#ffffff"
                row_alternate="#ffffff0d"
                text_strip_cursor="#71a8ffff"
                selected_text="#ffffff4d"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#eeeeee"
                    text="#a6a6a6"
                    text_hi="#ffffff"
                    header="#3b4252ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeSequenceEditor>
            </sequence_editor>
            <properties>
              <ThemeProperties
                match="#a27c35"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#eceff4"
                    text="#e5e9f0"
                    text_hi="#ffffff"
                    header="#2e3440ff"
                    header_text="#eceff4"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeProperties>
            </properties>
            <text_editor>
              <ThemeTextEditor
                line_numbers="#eceff4"
                line_numbers_background="#2e3440"
                selected_text="#4c566a"
                cursor="#ff0000"
                syntax_builtin="#bf616a"
                syntax_symbols="#d08770"
                syntax_special="#a3be8c"
                syntax_preprocessor="#b48ead"
                syntax_reserved="#c4753b"
                syntax_comment="#5e81ac"
                syntax_string="#ebcb8b"
                syntax_numbers="#88c0d0"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#eeeeee"
                    text="#e6e6e6"
                    text_hi="#ffffff"
                    header="#2e3440ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeTextEditor>
            </text_editor>
            <node_editor>
              <ThemeNodeEditor
                grid="#4c566a"
                node_outline="#ffffff72"
                node_selected="#d08770"
                node_active="#ffffff"
                wire="#444649a9"
                wire_inner="#d8dee9"
                wire_select="#eceff4b3"
                node_backdrop="#3b4252ff"
                converter_node="#5e81ac"
                color_node="#ebcb8b"
                group_node="#a3be8c"
                group_socket_node="#1a1a1a"
                frame_node="#3b4252cc"
                matte_node="#975b5b"
                distor_node="#749797"
                noodle_curving="2"
                grid_levels="3"
                dash_alpha="0.423913"
                input_node="#bf616a"
                output_node="#d08770"
                filter_node="#b48ead"
                vector_node="#b48ead"
                texture_node="#d08770"
                shader_node="#a3be8c"
                script_node="#084d4d"
                geometry_node="#00d7a4"
                attribute_node="#81a1c1"
                simulation_zone="#66416233"
                repeat_zone="#76512f33"
                foreach_geometry_element_zone="#33527f33"
                closure_zone="#7d7d3a33"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#eeeeee"
                    text="#e6e6e6"
                    text_hi="#ffffff"
                    header="#2e3440ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeNodeEditor>
            </node_editor>
            <outliner>
              <ThemeOutliner
                match="#b48ead"
                selected_highlight="#312510"
                active="#513e1b"
                selected_object="#2e3440"
                active_object="#2e3440"
                edited_object="#a3be8c66"
                row_alternate="#3b4252ff"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#333945"
                    title="#eceff4"
                    text="#d8dee9"
                    text_hi="#ffffff"
                    header="#333945ff"
                    header_text="#eeeeee"
                    header_text_hi="#eceff4"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeOutliner>
            </outliner>
            <info>
              <ThemeInfo
                info_selected="#3b5689"
                info_selected_text="#ffffff"
                info_error_text="#ffffff"
                info_warning_text="#ffffff"
                info_info_text="#ffffff"
                info_debug="#d3d3d3ff"
                info_debug_text="#000000"
                info_property="#3ace87ff"
                info_property_text="#ffffff"
                info_operator="#3ace87ff"
                info_operator_text="#ffffff"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#ffffff"
                    text="#c3c3c3"
                    text_hi="#ffffff"
                    header="#2e3440ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeInfo>
            </info>
            <preferences>
              <ThemePreferences>
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#eceff4"
                    text="#e5e9f0"
                    text_hi="#eceff4"
                    header="#2e3440ff"
                    header_text="#e5e9f0"
                    header_text_hi="#eceff4"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemePreferences>
            </preferences>
            <console>
              <ThemeConsole
                line_output="#88c0d0"
                line_input="#f2f2f2"
                line_info="#95d600"
                line_error="#bf616a"
                cursor="#ff0000"
                select="#ffffff30"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#eeeeee"
                    text="#e6e6e6"
                    text_hi="#ffffff"
                    header="#2e3440ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeConsole>
            </console>
            <clip_editor>
              <ThemeClipEditor
                grid="#3b4252ff"
                marker_outline="#000000"
                marker="#7f7f00"
                active_marker="#ffffff"
                selected_marker="#ffff00"
                disabled_marker="#7f0000"
                locked_marker="#7f7f7f"
                path_before="#ff0000"
                path_after="#0000ff"
                path_keyframe_before="#ffc4c4"
                path_keyframe_after="#c4c4ff"
                metadatabg="#000000"
                metadatatext="#ffffff"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#eceff4"
                    text="#a6a6a6"
                    text_hi="#ffffff"
                    header="#3b4252ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeClipEditor>
            </clip_editor>
            <topbar>
              <ThemeTopBar>
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#eceff4"
                    text="#e5e9f0"
                    text_hi="#576890"
                    header="#2e3440ff"
                    header_text="#eeeeee"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeTopBar>
            </topbar>
            <statusbar>
              <ThemeStatusBar>
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#eceff4"
                    text="#eceff4"
                    text_hi="#ffffff"
                    header="#2e3440ff"
                    header_text="#eceff4"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeStatusBar>
            </statusbar>
            <spreadsheet>
              <ThemeSpreadsheet
                row_alternate="#ffffff07"
                >
                <space>
                  <ThemeSpaceGeneric
                    back="#2e3440"
                    title="#eceff4"
                    text="#eceff4"
                    text_hi="#5e81ac"
                    header="#2e3440ff"
                    header_text="#eceff4"
                    header_text_hi="#ffffff"
                    >
                  </ThemeSpaceGeneric>
                </space>
              </ThemeSpreadsheet>
            </spreadsheet>
            <bone_color_sets>
              <ThemeBoneColorSet
                normal="#9a0000"
                select="#bd1111"
                active="#f70a0a"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#f74018"
                select="#f66913"
                active="#fa9900"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#1e9109"
                select="#59b70b"
                active="#83ef1d"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#0a3694"
                select="#3667df"
                active="#5ec1ef"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#a9294e"
                select="#c1416a"
                active="#f05d91"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#430c78"
                select="#543aa3"
                active="#8764d5"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#24785a"
                select="#3c9579"
                active="#6fb6ab"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#4b707c"
                select="#6a8691"
                active="#9bc2cd"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#f4c90c"
                select="#eec236"
                active="#f3ff00"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#1e2024"
                select="#484c56"
                active="#ffffff"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#6f2f6a"
                select="#9845be"
                active="#d330d6"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#6c8e22"
                select="#7fb022"
                active="#bbef5b"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#8d8d8d"
                select="#b0b0b0"
                active="#dedede"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#834326"
                select="#8b5811"
                active="#bd6a11"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#08310e"
                select="#1c430b"
                active="#34622b"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#000000"
                select="#000000"
                active="#000000"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#000000"
                select="#000000"
                active="#000000"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#000000"
                select="#000000"
                active="#000000"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#000000"
                select="#000000"
                active="#000000"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
              <ThemeBoneColorSet
                normal="#000000"
                select="#000000"
                active="#000000"
                show_colored_constraints="FALSE"
                >
              </ThemeBoneColorSet>
            </bone_color_sets>
            <collection_color>
              <ThemeCollectionColor
                color="#bf616a"
                >
              </ThemeCollectionColor>
              <ThemeCollectionColor
                color="#d08770"
                >
              </ThemeCollectionColor>
              <ThemeCollectionColor
                color="#ebcb8b"
                >
              </ThemeCollectionColor>
              <ThemeCollectionColor
                color="#a3be8c"
                >
              </ThemeCollectionColor>
              <ThemeCollectionColor
                color="#81a1c1"
                >
              </ThemeCollectionColor>
              <ThemeCollectionColor
                color="#b48ead"
                >
              </ThemeCollectionColor>
              <ThemeCollectionColor
                color="#c671b8"
                >
              </ThemeCollectionColor>
              <ThemeCollectionColor
                color="#7a6053"
                >
              </ThemeCollectionColor>
            </collection_color>
            <strip_color>
              <ThemeStripColor
                color="#e2605b"
                >
              </ThemeStripColor>
              <ThemeStripColor
                color="#f1a355"
                >
              </ThemeStripColor>
              <ThemeStripColor
                color="#f1dc55"
                >
              </ThemeStripColor>
              <ThemeStripColor
                color="#7bcc7b"
                >
              </ThemeStripColor>
              <ThemeStripColor
                color="#5db6ea"
                >
              </ThemeStripColor>
              <ThemeStripColor
                color="#8d59da"
                >
              </ThemeStripColor>
              <ThemeStripColor
                color="#c673b8"
                >
              </ThemeStripColor>
              <ThemeStripColor
                color="#7a5441"
                >
              </ThemeStripColor>
              <ThemeStripColor
                color="#5f5f5f"
                >
              </ThemeStripColor>
            </strip_color>
          </Theme>
          <ThemeStyle>
            <panel_title>
              <ThemeFontStyle
                points="12"
                character_weight="400"
                shadow="5"
                shadow_offset_x="0"
                shadow_offset_y="-1"
                shadow_alpha="0.5"
                shadow_value="0"
                >
              </ThemeFontStyle>
            </panel_title>
            <widget>
              <ThemeFontStyle
                points="11"
                character_weight="400"
                shadow="2"
                shadow_offset_x="0"
                shadow_offset_y="-1"
                shadow_alpha="0.5"
                shadow_value="0"
                >
              </ThemeFontStyle>
            </widget>
            <tooltip>
              <ThemeFontStyle
                points="11"
                character_weight="400"
                shadow="1"
                shadow_offset_x="0"
                shadow_offset_y="-1"
                shadow_alpha="0.5"
                shadow_value="0"
                >
              </ThemeFontStyle>
            </tooltip>
          </ThemeStyle>
        <
      '';
    };
  };
}
