{
  imports = [
    ./hyprland
    ./nvf
    ./stylix.nix
    ./env.nix
    ./git.nix
    ./kitty.nix
    ./fzf.nix
    ./zsh.nix
    ./swayimg.nix
    ./nh.nix
    ./swww.nix
    ./bat.nix
    ./waybar
    ./swaync.nix
    ./btop.nix
    ./oh-my-posh.nix
    ./lazygit.nix
    ./wlogout.nix
    ./spotify.nix
    ./discord.nix
    ./browser.nix
    ./godot.nix
    ./mangohud.nix
    ./lutris.nix
    ./fd.nix
    ./qt.nix
    ./gtk.nix
    ./xdg.nix
    ./mpv.nix
    ./cursor.nix
    ./networkmanager-dmenu.nix
    ./rofi.nix
    ./yazi.nix
  ];
}
