{
  imports = [
    ./stylix.nix
    ./audio.nix
    ./bluetooth.nix
    ./networking.nix
    ./nix.nix
    ./boot.nix
    ./timezone.nix
    ./user.nix
    ./keyboard.nix
    ./zram.nix
    ./hyprland.nix
    ./update.nix
    ./sudo.nix
    ./nixld.nix
    ./hardware.nix
    ./steam.nix
    ./gamemode.nix
    ./virtualization.nix
    ./mount.nix
    ./polkit.nix
    ./xdg.nix
    ./display-manager.nix
    ./openrgb.nix
    ./udev.nix
    ./env.nix
    ./rdp.nix
  ];
}
